# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1


# LOADING ALL FUNCTION DEFINITIONS:

. $PSScriptRoot\Clear-DpDisk.ps1
. $PSScriptRoot\Convert-DpDisk.ps1
. $PSScriptRoot\Format-DpVolume.ps1
. $PSScriptRoot\Get-DpDiskDetails.ps1
. $PSScriptRoot\Get-DpDisk.ps1
. $PSScriptRoot\Get-DpVhdDetails.ps1
. $PSScriptRoot\Get-DpVolume.ps1
. $PSScriptRoot\Mount-DpVHD.ps1
. $PSScriptRoot\New-DpVhdDiff.ps1
. $PSScriptRoot\New-DpVolume.ps1
. $PSScriptRoot\Initialize-DpDisk.ps1
. $PSScriptRoot\Set-DpVolume.ps1
. $PSScriptRoot\Get-DpPartition.ps1
. $PSScriptRoot\Test-DpDiskEmpty.ps1
. $PSScriptRoot\Merge-DpVhdDiffToParent.ps1
. $PSScriptRoot\Get-DpvhdInfo.ps1
. $PSScriptRoot\Get-FreeDriveLetter.ps1
